// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "IKnowEarth",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "IKnowEarth",
            targets: ["AppModule"],
            bundleIdentifier: "br.ufpe.cin.jfrjs.IKnowEarth",
            teamIdentifier: "3YK22GD7FS",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .asset("AccentColor"),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    
    targets: [
        .executableTarget(
         name: "AppModule",
         path: ".",
         resources: [
          .process("Resources")
         ]
        )
       ]
      )
